name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: auto
    steps:
    - uses: actions/checkout@v2

    - name: Install required packages
      run: sudo apt-get install -y libpam0g-dev
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build & Test
      run: make
